# 01_Module

## Project Jupyter

**Project Jupyter** is a nonprofit organization created to "develop **open-source software for interactive computing** across dozens of programming languages." Spun-off from IPython in 2014 by Fernando Pérez, Project Jupyter supports execution environments in several dozen languages. Project Jupyter's name is a reference to the three core programming languages supported by Jupyter, which are **Julia, Python and R**, and also an homage to Galileo's notebooks recording the discovery of the moons of Jupiter. Project Jupyter has developed and supported the interactive computing products **Jupyter Notebook**, Jupyter Hub, and **Jupyter Lab**, the next-generation version of Jupyter Notebook.

Installation options

1. Jupyter notebook on your local machine: [Anaconda installation link](https://docs.continuum.io/anaconda/install/)
2. Jupyter lab running on a cloud system: [Jupyter lab](http://jupyter.org/try)

## Basic Python

**example 1**

In [1]:
name = ['Mike', 'Rob', 'John', 'David']

In [2]:
'Kevin' in name

False

In [3]:
name.append('Kevin')

In [4]:
'Kevin' in name

True

**example 2**

In [5]:
major = ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME']

In [6]:
set(major)

{'CAEE', 'ME'}

In [7]:
major.count('CAEE')

3

**example 3**

In [8]:
score = [95, 85, 73, 86, 99]

In [9]:
type(name[0])

str

In [10]:
type(score[0])

int

**example 4**

In [11]:
SBC_course_test = name + major + score

In [12]:
SBC_course_test

['Mike',
 'Rob',
 'John',
 'David',
 'Kevin',
 'CAEE',
 'CAEE',
 'ME',
 'CAEE',
 'ME',
 95,
 85,
 73,
 86,
 99]

In [13]:
SBC_course=[name, major, score]

In [14]:
SBC_course

[['Mike', 'Rob', 'John', 'David', 'Kevin'],
 ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME'],
 [95, 85, 73, 86, 99]]

In [15]:
SBC_course[0]

['Mike', 'Rob', 'John', 'David', 'Kevin']

In [16]:
SBC_course[0][0]

'Mike'

**example 5**

In [17]:
len(score)

5

In [18]:
grade=[0] * len(score)

for i in range(len(score)):
    if score[i] > 90:
        grade[i] = 'A'
    elif score[i] > 80:
        grade[i] = 'B'
    else:
        grade[i] = 'C'

In [19]:
grade

['A', 'B', 'C', 'B', 'A']

In [20]:
SBC_course.append(grade)

In [21]:
SBC_course

[['Mike', 'Rob', 'John', 'David', 'Kevin'],
 ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME'],
 [95, 85, 73, 86, 99],
 ['A', 'B', 'C', 'B', 'A']]

## Basic Numpy

**example 6**

In [22]:
import numpy
numpy.__version__

'1.11.1'

In [23]:
import numpy as np

In [ ]:
np.<TAB>

In [24]:
np?

In [25]:
np.abs?

**example 7**

In [26]:
name

['Mike', 'Rob', 'John', 'David', 'Kevin']

In [27]:
type(name)

list

In [28]:
name = np.array(name)

In [29]:
type(name)

numpy.ndarray

In [30]:
type(name[0])

numpy.string_

**example 8**

In [31]:
SBC_course_test

['Mike',
 'Rob',
 'John',
 'David',
 'Kevin',
 'CAEE',
 'CAEE',
 'ME',
 'CAEE',
 'ME',
 95,
 85,
 73,
 86,
 99]

In [32]:
SBC_course_test = np.array(SBC_course_test).reshape((3,5))

In [33]:
SBC_course_test

array([['Mike', 'Rob', 'John', 'David', 'Kevin'],
       ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME'],
       ['95', '85', '73', '86', '99']], 
      dtype='|S5')

In [34]:
score_final = np.random.normal(75, 5, (5))

In [35]:
score_final

array([ 83.551713  ,  66.13776972,  73.59515509,  79.40521688,  74.65707183])

In [36]:
SBC_course_test=np.append(SBC_course_test,[score_final],axis=0)

**example 9**

In [37]:
SBC_course_test

array([['Mike', 'Rob', 'John', 'David', 'Kevin'],
       ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME'],
       ['95', '85', '73', '86', '99'],
       ['83.5517130037', '66.1377697153', '73.5951550943', '79.4052168826',
        '74.6570718307']], 
      dtype='|S32')

In [38]:
SBC_course_test[2:4]

array([['95', '85', '73', '86', '99'],
       ['83.5517130037', '66.1377697153', '73.5951550943', '79.4052168826',
        '74.6570718307']], 
      dtype='|S32')

In [39]:
scores = np.array(SBC_course_test[2:4],dtype=float)

In [40]:
scores

array([[ 95.        ,  85.        ,  73.        ,  86.        ,  99.        ],
       [ 83.551713  ,  66.13776972,  73.59515509,  79.40521688,
         74.65707183]])

In [41]:
avg_score = np.mean(scores,axis=0)

In [42]:
avg_score

array([ 89.2758565 ,  75.56888486,  73.29757755,  82.70260844,  86.82853592])

In [43]:
avg_score>80

array([ True, False, False,  True,  True], dtype=bool)

In [44]:
grade_final = np.where(avg_score>80, 'pass', 'fail')

In [45]:
grade_final

array(['pass', 'fail', 'fail', 'pass', 'pass'], 
      dtype='|S4')

In [46]:
SBC_course_test = np.append(SBC_course_test,[avg_score, grade_final],axis=0)

In [47]:
SBC_course_test

array([['Mike', 'Rob', 'John', 'David', 'Kevin'],
       ['CAEE', 'CAEE', 'ME', 'CAEE', 'ME'],
       ['95', '85', '73', '86', '99'],
       ['83.5517130037', '66.1377697153', '73.5951550943', '79.4052168826',
        '74.6570718307'],
       ['89.2758565019', '75.5688848577', '73.2975775471', '82.7026084413',
        '86.8285359154'],
       ['pass', 'fail', 'fail', 'pass', 'pass']], 
      dtype='|S32')

In [48]:
print("dimension: ", SBC_course_test.ndim)
print("shape: ", SBC_course_test.shape)
print("size: ", SBC_course_test.size)
print("filesize: ", SBC_course_test.nbytes, "bytes")

('dimension: ', 2)
('shape: ', (6, 5))
('size: ', 30)
('filesize: ', 960, 'bytes')


**example 10**

In [49]:
import random

[[random.random() for i in range(3)] for j in range(3)]

[[0.2869667966537762, 0.36502946321196117, 0.3360813456913454],
 [0.9030129950801347, 0.9798194218572507, 0.23636226611389177],
 [0.7957890714052092, 0.29238280192307264, 0.6758005741103522]]

In [50]:
np.random.random((3, 3))

array([[ 0.33956728,  0.71152941,  0.68024312],
       [ 0.83044575,  0.15201925,  0.66654469],
       [ 0.31355362,  0.25945585,  0.43059571]])

In [51]:
#from https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference
import time

size_of_vec = 1000000
#billion

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

(0.3049650192260742, 0.005097150802612305)
Numpy is in this example 59.8304878619 faster!


In [52]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 71.4 ms per loop
1000 loops, best of 3: 329 µs per loop


In [53]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 55 ms per loop
1000 loops, best of 3: 286 µs per loop


## Basic Python vs Numpy

- Size: Numpy data structures take up less space
- Performance: they have a need for speed and are faster than lists
- Functionality: SciPy and NumPy have optimized functions such as linear algebra operations built in.

## Google knows everything

- Direct google search: many blogs explains the procedures in detail
- [Stack Overflow](https://stackoverflow.com/)
- Youtube video!


- All you need to do is... searching with right keywords!

<img src="phd_comics.jpg">
<h5><center>Fig.1 Why programming? from phdcomics.com</center></h5>